# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Request" do
    optional :type, :enum, 1, "Request.RequestType"
    optional :node, :uint32, 2
    optional :time, :uint32, 3
  end
  add_enum "Request.RequestType" do
    value :REQUEST, 0
    value :GRANT, 1
    value :RELEASE, 2
  end
end

Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("Request").msgclass
Request::RequestType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Request.RequestType").enummodule
