// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_ENQUEUE     Message_Type = 0
	Message_REQUEST     Message_Type = 1
	Message_ACKNOWLEDGE Message_Type = 2
	Message_RELEASE     Message_Type = 3
)

var Message_Type_name = map[int32]string{
	0: "ENQUEUE",
	1: "REQUEST",
	2: "ACKNOWLEDGE",
	3: "RELEASE",
}
var Message_Type_value = map[string]int32{
	"ENQUEUE":     0,
	"REQUEST":     1,
	"ACKNOWLEDGE": 2,
	"RELEASE":     3,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	MsgType Message_Type `protobuf:"varint,1,opt,name=msg_type,json=msgType,enum=Message_Type" json:"msg_type,omitempty"`
	Pid     uint32       `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	Clock   uint32       `protobuf:"varint,3,opt,name=clock" json:"clock,omitempty"`
	Likes   uint32       `protobuf:"varint,4,opt,name=likes" json:"likes,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetMsgType() Message_Type {
	if m != nil {
		return m.MsgType
	}
	return Message_ENQUEUE
}

func (m *Message) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Message) GetClock() uint32 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *Message) GetLikes() uint32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterEnum("Message_Type", Message_Type_name, Message_Type_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xda, 0xc8, 0xc8, 0xc5, 0xee, 0x0b,
	0x11, 0x11, 0xd2, 0xe0, 0xe2, 0xc8, 0x2d, 0x4e, 0x8f, 0x2f, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x33, 0xe2, 0xd5, 0x83, 0xca, 0xe9, 0x85, 0x54, 0x16, 0xa4, 0x06, 0xb1, 0xe7,
	0x16, 0xa7, 0x83, 0x18, 0x42, 0x02, 0x5c, 0xcc, 0x05, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0xbc, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x72, 0x4e, 0x7e, 0x72, 0xb6, 0x04, 0x33, 0x58,
	0x0c, 0xc2, 0x01, 0x89, 0xe6, 0x64, 0x66, 0xa7, 0x16, 0x4b, 0xb0, 0x40, 0x44, 0xc1, 0x1c, 0x25,
	0x3b, 0x2e, 0x16, 0xb0, 0x29, 0xdc, 0x5c, 0xec, 0xae, 0x7e, 0x81, 0xa1, 0xae, 0xa1, 0xae, 0x02,
	0x0c, 0x20, 0x4e, 0x90, 0x6b, 0x60, 0xa8, 0x6b, 0x70, 0x88, 0x00, 0xa3, 0x10, 0x3f, 0x17, 0xb7,
	0xa3, 0xb3, 0xb7, 0x9f, 0x7f, 0xb8, 0x8f, 0xab, 0x8b, 0xbb, 0xab, 0x00, 0x13, 0x44, 0xd6, 0xc7,
	0xd5, 0x31, 0xd8, 0x55, 0x80, 0x39, 0x89, 0x0d, 0xec, 0x74, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xef, 0xb2, 0xf5, 0x6c, 0xcb, 0x00, 0x00, 0x00,
}
