# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "message.Message" do
    optional :msg_type, :enum, 1, "message.Message.Type"
    optional :amount, :uint32, 2
  end
  add_enum "message.Message.Type" do
    value :TRANSFER, 0
    value :MARKER, 1
  end
end

module Message
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("message.Message").msgclass
  Message::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("message.Message.Type").enummodule
end
