// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Value
	Message
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value_Type int32

const (
	Value_UNKNOWN Value_Type = 0
	Value_BUY     Value_Type = 1
	Value_SUPPLY  Value_Type = 2
	Value_JOIN    Value_Type = 3
	Value_LEAVE   Value_Type = 4
)

var Value_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "BUY",
	2: "SUPPLY",
	3: "JOIN",
	4: "LEAVE",
}
var Value_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"BUY":     1,
	"SUPPLY":  2,
	"JOIN":    3,
	"LEAVE":   4,
}

func (x Value_Type) String() string {
	return proto.EnumName(Value_Type_name, int32(x))
}
func (Value_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message_Type int32

const (
	Message_UNKNOWN  Message_Type = 0
	Message_PETITION Message_Type = 1
	Message_PROPOSE  Message_Type = 2
	Message_PROMISE  Message_Type = 3
	Message_ACCEPT   Message_Type = 4
	Message_ACCEPTED Message_Type = 5
	Message_NOTIFY   Message_Type = 6
	Message_QUERY    Message_Type = 7
)

var Message_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "PETITION",
	2: "PROPOSE",
	3: "PROMISE",
	4: "ACCEPT",
	5: "ACCEPTED",
	6: "NOTIFY",
	7: "QUERY",
}
var Message_Type_value = map[string]int32{
	"UNKNOWN":  0,
	"PETITION": 1,
	"PROPOSE":  2,
	"PROMISE":  3,
	"ACCEPT":   4,
	"ACCEPTED": 5,
	"NOTIFY":   6,
	"QUERY":    7,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Value struct {
	Type     Value_Type `protobuf:"varint,1,opt,name=type,enum=main.Value_Type" json:"type,omitempty"`
	Client   uint32     `protobuf:"varint,2,opt,name=client" json:"client,omitempty"`
	Sequence uint32     `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	Value    uint32     `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Value) GetType() Value_Type {
	if m != nil {
		return m.Type
	}
	return Value_UNKNOWN
}

func (m *Value) GetClient() uint32 {
	if m != nil {
		return m.Client
	}
	return 0
}

func (m *Value) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Value) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Message struct {
	Type   Message_Type `protobuf:"varint,1,opt,name=type,enum=main.Message_Type" json:"type,omitempty"`
	Epoch  uint32       `protobuf:"varint,3,opt,name=epoch" json:"epoch,omitempty"`
	Sender uint32       `protobuf:"varint,2,opt,name=sender" json:"sender,omitempty"`
	Ballot uint32       `protobuf:"varint,4,opt,name=ballot" json:"ballot,omitempty"`
	Value  *Value       `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_UNKNOWN
}

func (m *Message) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Message) GetSender() uint32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Message) GetBallot() uint32 {
	if m != nil {
		return m.Ballot
	}
	return 0
}

func (m *Message) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "main.Value")
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterEnum("main.Value_Type", Value_Type_name, Value_Type_value)
	proto.RegisterEnum("main.Message_Type", Message_Type_name, Message_Type_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4e, 0xb3, 0x40,
	0x14, 0x86, 0xbf, 0x81, 0x01, 0xfa, 0x9d, 0x5a, 0x33, 0x39, 0x69, 0x0c, 0x71, 0x55, 0x1b, 0x63,
	0xba, 0x62, 0x51, 0xd7, 0x2e, 0x6a, 0x1d, 0x13, 0xb4, 0x05, 0xa4, 0x50, 0xc3, 0x92, 0xd6, 0x89,
	0x36, 0xa1, 0x80, 0x85, 0x9a, 0xf4, 0x0e, 0xbc, 0x22, 0xaf, 0xcf, 0x0c, 0x3f, 0xa6, 0x26, 0xee,
	0xe6, 0x9d, 0x27, 0x73, 0xf2, 0x3e, 0x67, 0xa0, 0xb7, 0x15, 0x45, 0x11, 0xbf, 0x0a, 0x2b, 0xdf,
	0x65, 0x65, 0x86, 0x74, 0x1b, 0x6f, 0xd2, 0xe1, 0x17, 0x01, 0x6d, 0x19, 0x27, 0x7b, 0x81, 0x97,
	0x40, 0xcb, 0x43, 0x2e, 0x4c, 0x32, 0x20, 0xa3, 0xd3, 0x31, 0xb3, 0x24, 0xb6, 0x2a, 0x64, 0x05,
	0x87, 0x5c, 0xf8, 0x15, 0xc5, 0x33, 0xd0, 0xd7, 0xc9, 0x46, 0xa4, 0xa5, 0xa9, 0x0c, 0xc8, 0xa8,
	0xe7, 0x37, 0x09, 0xcf, 0xa1, 0x53, 0x88, 0xf7, 0xbd, 0x48, 0xd7, 0xc2, 0x54, 0x2b, 0xf2, 0x93,
	0xb1, 0x0f, 0xda, 0x87, 0x9c, 0x63, 0xd2, 0x0a, 0xd4, 0x61, 0x78, 0x03, 0x54, 0xce, 0xc5, 0x2e,
	0x18, 0xa1, 0xf3, 0xe8, 0xb8, 0xcf, 0x0e, 0xfb, 0x87, 0x06, 0xa8, 0xb7, 0x61, 0xc4, 0x08, 0x02,
	0xe8, 0x8b, 0xd0, 0xf3, 0x66, 0x11, 0x53, 0xb0, 0x03, 0xf4, 0xc1, 0xb5, 0x1d, 0xa6, 0xe2, 0x7f,
	0xd0, 0x66, 0x7c, 0xb2, 0xe4, 0x8c, 0x0e, 0x3f, 0x15, 0x30, 0xe6, 0xb5, 0x10, 0x5e, 0xfd, 0xaa,
	0x8e, 0x75, 0xf5, 0x06, 0x1e, 0x97, 0xef, 0x83, 0x26, 0xf2, 0x6c, 0xfd, 0xd6, 0x34, 0xac, 0x83,
	0x54, 0x2a, 0x44, 0xfa, 0x22, 0x76, 0xad, 0x52, 0x9d, 0xe4, 0xfd, 0x2a, 0x4e, 0x92, 0xac, 0x6c,
	0x7a, 0x37, 0x09, 0x2f, 0x5a, 0x1d, 0x6d, 0x40, 0x46, 0xdd, 0x71, 0xf7, 0x68, 0x53, 0xad, 0x5b,
	0xf2, 0x97, 0xdb, 0x09, 0x74, 0x3c, 0x1e, 0xd8, 0x81, 0xed, 0x3a, 0x8c, 0x48, 0xe4, 0xf9, 0xae,
	0xe7, 0x2e, 0x38, 0x53, 0x9a, 0x30, 0xb7, 0x17, 0x9c, 0xa9, 0x52, 0x7d, 0x32, 0x9d, 0x72, 0x2f,
	0x60, 0x54, 0xbe, 0xa9, 0xcf, 0xfc, 0x8e, 0x69, 0x92, 0x38, 0x6e, 0x60, 0xdf, 0x47, 0x4c, 0x97,
	0xab, 0x78, 0x0a, 0xb9, 0x1f, 0x31, 0x63, 0xa5, 0x57, 0x1f, 0x7a, 0xfd, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x9f, 0xb4, 0x01, 0xb6, 0xe1, 0x01, 0x00, 0x00,
}
