// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_S_PROPOSE Message_Type = 0
	Message_R_PROPOSE Message_Type = 1
	Message_S_ACCEPT  Message_Type = 2
	Message_R_ACCEPT  Message_Type = 3
	Message_S_NOTIFY  Message_Type = 4
)

var Message_Type_name = map[int32]string{
	0: "S_PROPOSE",
	1: "R_PROPOSE",
	2: "S_ACCEPT",
	3: "R_ACCEPT",
	4: "S_NOTIFY",
}
var Message_Type_value = map[string]int32{
	"S_PROPOSE": 0,
	"R_PROPOSE": 1,
	"S_ACCEPT":  2,
	"R_ACCEPT":  3,
	"S_NOTIFY":  4,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	Type  Message_Type `protobuf:"varint,1,opt,name=type,enum=main.Message_Type" json:"type,omitempty"`
	Node  uint32       `protobuf:"varint,2,opt,name=node" json:"node,omitempty"`
	Epoch uint32       `protobuf:"varint,3,opt,name=epoch" json:"epoch,omitempty"`
	Value uint32       `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_S_PROPOSE
}

func (m *Message) GetNode() uint32 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *Message) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Message) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterEnum("main.Message_Type", Message_Type_name, Message_Type_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0x3a, 0xc8, 0xc8, 0xc5, 0xee, 0x0b, 0x11, 0x17, 0x52, 0xe3, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd2, 0x03, 0x29, 0xd0, 0x83, 0x4a, 0xea, 0x85, 0x54,
	0x16, 0xa4, 0x06, 0x81, 0xe5, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0xf2, 0x53, 0x52, 0x25, 0x98, 0x14,
	0x18, 0x35, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0x82, 0xfc, 0xe4, 0x0c, 0x09,
	0x66, 0xb0, 0x20, 0x84, 0x03, 0x12, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x81, 0x88, 0x82,
	0x39, 0x4a, 0x7e, 0x5c, 0x2c, 0x20, 0xd3, 0x84, 0x78, 0xb9, 0x38, 0x83, 0xe3, 0x03, 0x82, 0xfc,
	0x03, 0xfc, 0x83, 0x5d, 0x05, 0x18, 0x40, 0xdc, 0x20, 0x38, 0x97, 0x51, 0x88, 0x87, 0x8b, 0x23,
	0x38, 0xde, 0xd1, 0xd9, 0xd9, 0x35, 0x20, 0x44, 0x80, 0x09, 0xc4, 0x0b, 0x82, 0xf1, 0x98, 0x21,
	0x72, 0x7e, 0xfe, 0x21, 0x9e, 0x6e, 0x91, 0x02, 0x2c, 0x49, 0x6c, 0x60, 0x0f, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x60, 0xa5, 0x02, 0xe8, 0xe1, 0x00, 0x00, 0x00,
}
