# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Message" do
    optional :type, :enum, 1, "Message.Type"
    optional :node, :uint32, 2
    optional :time, :uint32, 3
  end
  add_enum "Message.Type" do
    value :ENQUEUE, 0
    value :REQUEST, 1
    value :ACKNOWLEDGE, 2
    value :RELEASE, 3
  end
end

Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("Message").msgclass
Message::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("Message.Type").enummodule
